### ISSUE TITLE
可以给一个java版本的教程吗？ 现在用kotlin语法都不一样了

### ISSUE THREAD

**Issue by jlala** [musicode/react-native-pure-umeng-push#1]

**Comment by musicode** [comment]
抱歉啊，不用 java 很多年，估计再也不会用了...

**Comment by charmtiger** [comment]
@musicode  常规的 rn 的项目，可以直接使用你 Readme 中安卓的部分代码吗？类似 fun 这种 是不是 kotlin 😂

**Comment by musicode** [comment]
我所有的库都是 kotlin，明明 kotlin 简洁又好用，为啥我要用 java..

**Comment by charmtiger** [comment]
我使用您的库，是不是要把原来的 MainApplication.java 改成 MainApplication.kt , 或者只要把 onCreate 方法内的 代码复制就行了，或者自己把 fun 这种 kotlin 的代码 改成 java 的 对吧？不好意思 确实不懂 kotlin 跟 java

**Comment by musicode** [comment]
1. 建议优先用 [这里](https://github.com/react-native-hero) 的库，我会把自己用了很长时间且没有设计缺陷的库迁移过去，因此质量更高
2. kotlin 可以用 android studio 自带功能，把 java 自动转化成 kotlin，然后把我贴的代码拷到对应位置就行，此外需要 import 相关依赖

**Comment by charmtiger** [comment]
膜拜

**Comment by charmtiger** [comment]
你代码写的真棒

**Comment by musicode** [comment]
有啥 bug再说啦，类似不会 Kotlin 这种就别问了，真没空教...

**Comment by charmtiger** [comment]
我懂得，不会打扰了，老白嫖党了

**Comment by jlala** [comment]
> 我懂得，不会打扰了，老白嫖党了

你弄好了吗？ 我后来没有使用这个，我自己通过官方文档集成了，但现在就是获取不到devicetoken，能交流一下吗？wx：lxx451

**Comment by charmtiger** [comment]
@jlala  我还没有动手，过两天会试一下，现在在忙别的

**Comment by jlala** [comment]
> @jlala 我还没有动手，过两天会试一下，现在在忙别的

好呢好呢
